### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by vitaly-t**
somewhat wrong choice of methods... ;)

### CODE REVIEW

**Comment by vitaly-t** [comment]
The choice of the db method wouldn't have any effect on that. The problem must have been elsewhere :wink:

**Comment by vitaly-t** [comment]
Also, rather than querying and and enumerating through elements, see convenience methods [map](http://vitaly-t.github.io/pg-promise/Database.html#.map) and [each](http://vitaly-t.github.io/pg-promise/Database.html#.each) :wink:

**Comment by tabidots** [comment]
Can I ask which lines you are referring to? I had originally scratched up a first draft with some really ugly for-loops, but I already replaced them with map and forEach.

**Comment by vitaly-t** [comment]
In a few places where you first execute a query, and then do `.map` on the result. Instead, you can do `db.map`, with a mapper, which simplifies the whole thing, i.e. it re-maps the data automatically. Or for simple iteration, there is `db.each` ;) their logic is the same as those used for arrays ;) read the API i gave links for, they have examples there ;)

**Comment by tabidots** [comment]
Got it. Thanks! I had clicked those links, but I was little a confused because I didn't realize the code at the top was the "bad" code.

**Pull request merged**
